apiVersion: batch/v1
kind: Job
metadata:
  name: busybox-once
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ['sh', '-c', 'echo Hello ; sleep 5']
      restartPolicy: Never
