apiVersion: batch/v1
kind: CronJob
metadata:
  name: busybox-cron
spec:
  schedule: "*/2 * * * *"  # every 2 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: busybox
            image: busybox
            command: ["sh", "-c", "echo Running task"]
          restartPolicy: Never
